runtime: nodejs
env: flex
env_variables: 
  mongoDB: mongodb+srv://ratch_admin_06:Loona0607@cluster0-jdb4r.mongodb.net/test?retryWrites=true&w=majority

instance_class: F2

handlers:

- url: /favicon\.ico
  static_files: public/favicon.ico
  upload: public/favicon\.ico

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
